# Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [3]:
#!pip install numpy

import numpy as np

# create array using numpy
# create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## one row  and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
## 2 d array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
## attributes of numpy

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("shape:",arr.shape) #output:(2,3)
print("number of dimensions:",arr.size)
print("size (number of elements):",arr.size)
print("data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions: 6
size (number of elements): 6
data type: int32
Item size (in bytes): 4


In [13]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### element wise addition
print("addition:",arr1+arr2)

## element wise substraction
print("substraction:",arr1-arr2)

## element wise multiplication
print("multiplication:",arr1 * arr2)

#element wise division
print("division:",arr1/arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [14]:
## universal function

arr= np.array([2,3,4,5,6])

## square root

print(np.sqrt(arr))

##expotential
print(np.exp(arr))

## sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [16]:
## array silicing and indexing

arr = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("array: \n",arr)

array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(arr[0][0])
print(arr[0:2,1:])

1
[[2 3 4]
 [6 7 8]]


In [22]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
## modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [26]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [27]:
## statistical concepts --normaliztion
# to have a mean of 0 and standad deviation of 1
data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data
normalized_data = (data - mean) / std_dev
print("normalized data:", normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean = np.mean(data)
print("mean:",mean)

median = np.median(data)
print("median:",median)

std_dev = np.std(data)
print("standard deviation:", std_dev)

variance = np.var(data)
print("variance:",variance)

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [33]:
## logical operators

data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])